name: DEPLOYING ON RENDER

on:
  push: 
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install my code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: install packages
        run: npm install

      - name: build
        run: npm run build

      - name: deploy on render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}